# Generated by Django 5.2.13 on 2026-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='edu_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
